name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [9.2.8, 9.4.7]
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal update
      - run: cabal build all
      - run: cabal test all
